[data]
train_test_split = 0.2
random_state = 42

[preprocessing]
min_df = 5  # Minimum document frequency for TF-IDF vectorizer
max_features = 10000  # Maximum number of features for TF-IDF vectorizer
stop_words = "english"  # Stop words language
lowercase = true
remove_punctuation = true
stem_words = true

[model]
type = "naive_bayes"  # Options: "naive_bayes", "svm", "random_forest", "logistic_regression"
cross_validation_folds = 5

[naive_bayes]
alpha = 1.0  # Smoothing parameter
fit_prior = true

[svm]
C = 1.0  # Regularization parameter
kernel = "linear"  # Options: "linear", "poly", "rbf", "sigmoid"
gamma = "scale"  # Options: "scale", "auto" or float

[random_forest]
n_estimators = 100
max_depth = null  # null for unlimited depth
min_samples_split = 2
min_samples_leaf = 1

[logistic_regression]
C = 1.0  # Regularization parameter
penalty = "l2"  # Options: "l1", "l2", "elasticnet", "none"
solver = "lbfgs"  # Options: "newton-cg", "lbfgs", "liblinear", "sag", "saga"
max_iter = 100

[evaluation]
metrics = ["accuracy", "precision", "recall", "f1", "roc_auc"]
